### ISSUE TITLE
IE9

### ISSUE THREAD

**Issue by jbadeau** [mgechev/angular-aop#18]
Hello,

This lib seems not to work with IE9. Is IE9 supported?

**Comment by mgechev** [comment]
Hi @jbadeau,

AngularAOP should work on IE9 unfortunately I don't have a machine with version of IE <11, so I can't test it.

Would you share the stack trace in the issue?

**Comment by jbadeau** [comment]
The IE9 stacktrace:

13:19:34 ERROR - {anonymous}(?)
printStackTrace(#object)
printStacktrace(["$stateChangeError",?])
{anonymous}("$stateChangeError",?)
{anonymous}(#object,#object,#object,#object,#object,?)
{anonymous}("$stateChangeError",#object,#object,#object,#object,?)
{anonymous}(?)
processQueue(#object)
{anonymous}(?,undefined)
{anonymous}(#function,undefined) $stateChangeError
Exception: Object expected

the error is caused because the service (e.g fooService) that is decorated is unknown. If I remove the aspects the service is injected. @injector.get('fooService') also fails
resolve : {
    foo : ['fooService', function(fooService)]
}

both the config and service time decoration styles fail

**Comment by eralha** [comment]
I can confirm that http://plnkr.co/edit/0ThG5wpmWByIXY1db9m2?p=preview is showing error's on IE9:
Error: Unspecified error.undefined 
TypeError: Object doesn't support property or method 'apply'undefined

**Comment by mgechev** [comment]
Thanks! I'll fix it as soon as possible.

**Comment by jbadeau** [comment]
thanx for the fast response :)

**Comment by mgechev** [comment]
Test with the master branch in order to verify whether the issue is fixed.

**Comment by jbadeau** [comment]
Yes, it fixed my issue :) Thanx

**Comment by jbadeau** [comment]
Do you plan to make a patch release 0.4.1 or something?

**Comment by mgechev** [comment]
Yes, in 30ish min it'll be up & running.

**Comment by mgechev** [comment]
[Here it is!](https://github.com/mgechev/angular-aop/releases)
