### ISSUE TITLE
joinpoint.proceed()

### ISSUE THREAD

**Issue by jbadeau** [mgechev/angular-aop#19]
Hi,

This issue is for a feature

I would like to have a way to change the args in the join-point. Some AOP lib have something like:

```
joinpoint.proceed(newArg1, newArg2, ...)
```
where:

- When, called, causes the original method to be invoked
- When called without arguments, the original arguments will be passed.
- When called with arguments, they will be passed
*instead of* the original arguments

I currently am forced to modify the joinpoint.args which is not very clean and also does not allow aspects like memoize as the original method is always invoked.

Cheers,
Jose

**Comment by mgechev** [comment]
This feature makes sense to me. I'll add it to the roadmap.

**Comment by mgechev** [comment]
Here's more flexible version of using [AOP with JavaScript](https://github.com/mgechev/aspect.js).

This project is no longer maintained.
