### ISSUE TITLE
How can I use the library for AOP on every controller and directive function call?

### ISSUE THREAD

**Issue by geetee24** [mgechev/angular-aop#21]
Please provide an example using AngularAOP to intercept every controller and directive methods()

**Comment by geetee24** [comment]
Please provide an example using AngularAOP to intercept every controller and directive methods()

**Comment by mgechev** [comment]
Take a look at [aspect.js](https://github.com/mgechev/aspect.js), which is more generic library. Angular-aop supports services, factories and providers only.

**Comment by geetee24** [comment]
Thanks.  can it be used to intercept every function in my controllers and directives?

**Comment by geetee24** [comment]
And can aspect js work on EMAC 5 browsers?  Not just 6?

**Comment by mgechev** [comment]
Yes. You can use any transpiler which provides ECMAScript decorators' support.

The output is ES5.
